# Ex 1/3

In [3]:
import numpy as np

In [7]:
def MultiMat (Mat1,Mat2):
    
    Mat3=Mat1*Mat2 #that simple or is there anything else we're supposed to do here?
    
    return (Mat3)

In [16]:
RND1 = np.random.rand(3,3)
RND2 = np.random.rand(3,3)

Sol = MultiMat(RND1,RND2)

#print(RND1)
#print(RND2)
print(Sol)


[[0.25121578 0.70909042 0.03806506]
 [0.181885   0.80006486 0.31013526]
 [0.28729442 0.17313728 0.01115979]]
